### ISSUE TITLE
Chinese translation of the workshop report

### ISSUE THREAD

**Issue by xueyuanjia** [w3c/strong-authentication-and-identity-workshop#27]
Hi,

The Chinese translation of this workshop report is at:
https://github.com/xueyuanjia/strong-authentication-and-identity-workshop/blob/master/report.zh.md

Would you like to copy/put it under this repo and link it to the report [English page](https://www.w3.org/Security/strong-authentication-and-identity-workshop/report.html)? W3C/China is distributing the report to local channels.

Thank you!
Xueyuan

**Comment by wseltzer** [comment]
Wow, cool! Thanks @xueyuanjia 
I'll be glad to import it here and link it from the English

**Comment by xueyuanjia** [comment]
Thank you very much 🎉  @wseltzer

**Comment by xueyuanjia** [comment]
If it's also possible to display the [report.zh](https://www.w3.org/Security/strong-authentication-and-identity-workshop/report.zh.html) page's header, sponsor, footer in Chinese, the translations are at:
* [header](https://github.com/xueyuanjia/strong-authentication-and-identity-workshop/blob/master/_includes/header.zh.html)
* [sponsor](https://github.com/xueyuanjia/strong-authentication-and-identity-workshop/blob/master/_includes/host_sponsors.zh.html)
* [footer](https://github.com/xueyuanjia/strong-authentication-and-identity-workshop/blob/master/_layouts/home.zh.html)

**Comment by wseltzer** [comment]
@xueyuanjia the way I imported your changes, they blew away the original English files. I replaced those, but haven't yet figured out what I need to update in the templating system to get the header/footer/sidebars in Chinese.

**Comment by xueyuanjia** [comment]
The current Chinese page looks ok, informative enough. Thanks @wseltzer
